### PR TITLE
Change hash randomizing string name to randomHash (from key)

### PR DESCRIPTION
**Pull request by khyberspache**

### CODE REVIEW

**Review by privateducky — COMMENTED** [review]
Do we need to change the text on the training flag?

**Review by privateducky — COMMENTED** [review]
Couple questions

**Comment by privateducky** [comment]
@khyberspache bump

**Comment by privateducky** [comment]
@khyberspache is this ready?? :) see questions inline above

**Comment by khyberspache** [comment]
https://github.com/preludeorg/training/pull/107

**Pull request merged**
